import io
import os
import json
import numpy as np
import torch
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image
from fastapi import FastAPI, File, UploadFile, Query, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sklearn.metrics.pairwise import cosine_similarity

app = FastAPI(
    title="ShopSphere ML Microservice",
    description="MobileNetV3 feature extraction and cosine visual similarity search",
    version="1.0.0"
)

# Enable CORS for Next.js frontend calls
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global variables for model and in-memory embeddings index
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = None
INDEX_FILE = os.path.join(os.path.dirname(__file__), "embeddings.json")
product_index = []  # List of {"id": str, "embedding": list}

# Standard ImageNet pre-processing transform for MobileNetV3
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


def load_model():
    """Loads pre-trained MobileNetV3 with classification head stripped for embeddings."""
    global model
    weights = models.MobileNet_V3_Small_Weights.DEFAULT
    base_model = models.mobilenet_v3_small(weights=weights)
    base_model.classifier = base_model.classifier[:-1]  # Exclude last linear layer
    base_model.eval()
    model = base_model.to(device)


def load_embeddings():
    """Loads pre-computed product embeddings generated by indexer.py."""
    global product_index
    if os.path.exists(INDEX_FILE):
        try:
            with open(INDEX_FILE, "r", encoding="utf-8") as f:
                product_index = json.load(f)
            print(f"Loaded {len(product_index)} indexed product embeddings.")
        except Exception as e:
            print(f"Failed to load embeddings index: {e}")
            product_index = []
    else:
        print(f"Embeddings file '{INDEX_FILE}' not found. Run indexer.py to generate it.")
        product_index = []


@app.on_event("startup")
def startup_event():
    load_model()
    load_embeddings()


def extract_features(image_bytes: bytes) -> np.ndarray:
    """Passes an image through MobileNetV3 to extract a normalized feature vector."""
    try:
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid image payload.")

    tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        embedding = model(tensor).squeeze().cpu().numpy()

    norm = np.linalg.norm(embedding)
    if norm > 0:
        embedding = embedding / norm

    return embedding


@app.get("/")
def health_check():
    return {
        "status": "healthy",
        "service": "ShopSphere ML Microservice",
        "indexed_items": len(product_index),
    }


@app.post("/search")
async def visual_search(
    file: UploadFile = File(...),
    top_k: int = Query(default=8, ge=1, le=50)
):
    """
    Accepts an uploaded image, extracts its embedding vector,
    and returns top_k nearest products ranked by cosine similarity.
    """
    if len(product_index) == 0:
        load_embeddings()

    if len(product_index) == 0:
        return {
            "results": [],
            "message": "Product index is empty. Please run indexer.py to index products."
        }

    contents = await file.read()
    query_vector = extract_features(contents).reshape(1, -1)

    index_ids = [item["id"] for item in product_index]
    index_matrix = np.array([item["embedding"] for item in product_index])

    similarities = cosine_similarity(query_vector, index_matrix)[0]

    # Rank products descending by similarity
    ranked_indices = np.argsort(similarities)[::-1][:top_k]

    results = []
    for idx in ranked_indices:
        results.append({
            "id": index_ids[idx],
            "score": round(float(similarities[idx]), 4)
        })

    return {"results": results}


@app.get("/recommendations/{product_id}")
def get_recommendations(
    product_id: str,
    top_k: int = Query(default=4, ge=1, le=20)
):
    """Returns visually similar items for a specific product detail page."""
    if len(product_index) == 0:
        load_embeddings()

    target_item = next((item for item in product_index if str(item["id"]) == str(product_id)), None)
    if not target_item:
        raise HTTPException(status_code=404, detail="Product ID not found in embeddings index.")

    target_vector = np.array(target_item["embedding"]).reshape(1, -1)
    
    other_items = [item for item in product_index if str(item["id"]) != str(product_id)]
    if not other_items:
        return {"results": []}

    other_ids = [item["id"] for item in other_items]
    other_matrix = np.array([item["embedding"] for item in other_items])

    similarities = cosine_similarity(target_vector, other_matrix)[0]
    ranked_indices = np.argsort(similarities)[::-1][:top_k]

    results = []
    for idx in ranked_indices:
        results.append({
            "id": other_ids[idx],
            "score": round(float(similarities[idx]), 4)
        })

    return {"results": results}